
 --SELECT sum(total_verified_loss) as total_loss FROM public.sba_disaster_loan_data  where fema_disaster_number ='4085'
 -- = 3,939,227,624 - Original sba total verified loss
 -- = 3,935,992,730 - 4 million less in tract mapping due to removing water only tracts


INSERT INTO severe_weather.details(
  begin_yearmonth,
  begin_day, 
  begin_time,
  end_yearmonth,
  end_day,
    end_time,
    episode_id,
    event_id,
    state,
    state_fips,
    year,
    month_name,
    event_type,
    cz_type,
    cz_fips,
    cz_name,
    wfo,
    begin_date_time,
    cz_timezone,
    end_date_time,
    injuries_direct,
    injuries_indirect,
    deaths_direct,
    deaths_indirect,
    damage_property,
    damage_crops,
    source,
    magnitude,
    magnitude_type,
    flood_cause,
    category,
    tor_f_scale,
    tor_length,
    tor_width,
    tor_other_wfo,
    tor_other_cz_state,
    tor_other_cz_fips,
    tor_other_cz_name,
    begin_range,
    begin_azimuth,
    begin_location,
    end_range,
    end_azimuth,
    end_location,
    begin_lat,
    begin_lon,
    end_lat,
    end_lon,
    episode_narrative,
    event_narrative,
    data_source,
    begin_coords_geom,
    end_coords_geom,
    property_damage,
    crop_damage,
    geoid,
    cousub_geoid
)
select
201210 as begin_yearmonth,
29 as begin_day,
1219 as begin_time,
201210 as end_yearmonth,
29 as end_day,
1519 as end_time,
69179 as episode_id,
2147483647 - row_number() over() as event_id,
'NEW YORK' as state,
36 as state_fips,
2012 as year,
'October' as month_name,
'Hurricane Flood' as event_type,
'Z' as cz_type,
cz_fips,
'' as cz_name,
'ALY' as wfo,
'2012-10-29 12:19:00' as begin_date_time,
'EST-5' as cz_timezone,
'2012-10-29 15:19:00' as end_date_time,
0 as injuries_direct,
0 as injuries_indirect,
0 as deaths_direct,
0 as deaths_indirect,
'' as damage_property,
'' as damage_crops,
'Small Business Administration' as source,
null as magnitude,
'' as magnitude_type,
'' as flood_cause,
'' as category,
'' as tor_f_scale,
null as tor_length,
null as tor_width,
'' as tor_other_wfo,
'' as tor_other_cz_state,
'' as tor_other_cz_fips,
'' as tor_other_cz_name,
null as begin_range,
'' as begin_azimuth,
'' as begin_location,
null as end_range,
'' as end_azimuth,
'' as end_location,
null as begin_lat,
null as begin_lon,
null as end_lat,
null as end_lon,
'episode narrative' as episode_narrative,
'event narrative' as event_narrative,
'CSV' as data_source,
null as begin_coords_geom,
null as end_coords_geom,
property_damage,
0 as crop_damage,
geoid,
'' as cousub_geoid
from 
(select
cast(substring(unnest(tracts) from 3 for 3) as int) as cz_fips,
CAST(sum(total_loss/num_tracts) as INT) as property_damage,
unnest(tracts) as geoid,
'' as cousub_geoid
from
(select a.geoid10 as zip, array_agg(b.geoid) as tracts, sum(c.total_loss) / count(a.geoid10) as total_loss, count(a.geoid10) as num_tracts
  from geo.cb_2017_us_zcta510 as a
  join 
       geo.tl_2017_36_tract  as b
       on st_intersects(a.geom,b.geom) and  b.aland > 0
  join (                                                                                    
  SELECT damaged_property_zip_code as zip, sum(total_verified_loss) as total_loss
  FROM public.sba_disaster_loan_data  where fema_disaster_number ='4085' group by damaged_property_zip_code
  ) c on c.zip = a.geoid10 
 group by a.geoid10) byZip
 group by geoid) as z
